export ASBINARY=C:\Program Files\BrAutomation\As27000en\Bin
export VCCBuildAll=1
export VCCASPROJECTPATH='c:\projects\google~1\trunk\br\bth41z\bth41_~1\41_065a.pgp'
export CPUNAME=BTH41_Z1
export VCINI=C:\projects\GOOGLE~1\trunk\br\bth41z\BTH41_~1\41_065a.pgp\pgm\BTH41_Z1\CPU\VISUAL~1\VC.ini
export VCPATH=c:\program files\brautomation\as27000en\as\vc
export VCPROJECTPATH='C:\projects\ googlesvn\trunk\br\bth41z\bth41_pp065\41_065a.pgp\pgm\BTH41_Z1\CPU'
export VCOBJECT=GUI_01
ROOTMAKE='$(VCPATH)\make\makefile'
export MAKE='C:/Program Files/BrAutomation/As27000en/as/gnuinst/bin/make.exe'
export VCCFLAGS=-w 3 -p1 66 -p2 66 -p3 0
export VCRTADVOPT=
COMPRESS_CCF=0

.PHONY: modules all

modules: 
	@$(MAKE) --win32 -s -f $(ROOTMAKE)

all: 
	@$(MAKE) --win32 -s -f $(ROOTMAKE) all
